---
:global:

Puppetfile:
  forge_url: http://forge.enterprisemodules.com
  format:    "%-50s,%s"
  shared_generic:
    puppetlabs-stdlib:
      version: 4.18.0
    saz-limits:
      version: 2.5.0
    saz-timezone:
      version: 4.0.1
    puppet-archive:
      version: 2.2.0
  shared_em:
    easy_type:
      version: 2.3.4
  shared_local:
    - role
    - profile
    - em_license
    - software
